<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PuntoDeVentaLibreria.Domain\PuntoDeVentaLibreria.Domain.csproj" />
    <ProjectReference Include="..\PuntoDeVentaLibreria.Application\PuntoDeVentaLibreria.Application.csproj" />
    <ProjectReference Include="..\PuntoDeVentaLibreria.Infrastructure\PuntoDeVentaLibreria.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="WPF-UI" Version="4.3.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
