<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>MR_SYS_KeyGen</AssemblyName>
    <RootNamespace>MR_SYS_KeyGen</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PuntoDeVentaLibreria.Application\PuntoDeVentaLibreria.Application.csproj" />
  </ItemGroup>

</Project>
